name: Update RSS Feed

on:
  schedule:
  - cron: '*/30 8-18 * * 1-5'
  workflow_dispatch:     # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen

      - name: Run monitor script
        run: python monitor.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [ -d docs ]; then git add docs/*; fi
          git diff --cached --quiet || git commit -m "Update RSS feed"
          git push
